# fly.toml app configuration file generated for tg-node-mini-app on 2024-06-13T15:09:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tg-node-mini-app'
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
app = "node ./main.js"


[build.args]
NODE_ENV = "production"

[build]
